services:
  # A Docker web service
  - type: web
    name: python1-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
